### ISSUE TITLE
Removing an event handler as part of handling an event will cause further events from the same trigger to not be handled.

### ISSUE THREAD

**Issue by ghost** [shadowmint/unity-n-events#2]
This issue came up when an event handler for an event disables the game object. In the `OnDisable()` method of that class, the event handler for the event that was handled that disabled the GameObject is unsubscribed. I believe this causing the action list to be modified in a way that the next event handler is not being iterated over due to the list size changing when an event is removed. 

If the event handler was not removed as part of handling the event, the next event handler would be called correctly.

**Comment by shadowmint** [comment]
@pinecleandog yup, spot on. 

Fixed in 1.1.3; there's a regression test covering the issue at https://github.com/shadowmint/unity-n-events/blob/master/src/n-events/Editor/Regressions/Regression02.cs, let me know if you find any edge cases where you see any breakage.

**Comment by ghost** [comment]
I had a look at the solution, that looks like it will create a considerable amount of garbage each time you trigger an event.

**Comment by shadowmint** [comment]
I can't see obvious alternative, can you?

For event dispatching not to be affected by altering the event list either
you need to clone the list or lock it, which would prevent event handlers
being disposed during events.

This isn't a high throughput real time event stream, its just high level
glue. If cloning an array of action pointers introduces unacceptable perf
regressions I recommend using some kind of custom fixed size array event
queues instead of this library.

**Comment by ghost** [comment]
Nothing I can think of off the top of my head without knowing exactly which indices have been removed. It makes sense to do it that way, I'd just prefer to avoid frequent GC.Collect triggers where possible.

**Comment by lordmortis** [comment]
Can't we, instead of doing a `.ToArray()` place each element of the _actions into another list for iteration? that should stop the allocation and still not fail due to modification of a list while we iterate through it?

**Comment by lordmortis** [comment]
Ugh. It was pointed out to me that the above has zero chance of working :/

**Comment by shadowmint** [comment]
I'm kind of skeptical it really makes much difference, but I've pushed 1.1.4 with:
https://github.com/shadowmint/unity-n-events/commit/495327de3f05ba024fdb96fc3ebe31ce1a5afa48

It now uses a sliding buffer to hold the action queue which gets reallocated when it needs to grow; it's slightly faster but also uses slightly more memory for the buffer when the number of event handlers is very large.

I can't really see any other options, but feel free to open a PR if you think of one.
